#define D3DFVF_CUSTOMVERTEX (D3DFVF_XYZRHW | D3DFVF_DIFFUSE | D3DFVF_TEX1)



enum TEXTURE
{
	BACKGROUND_TEX,
	TEXTURE_MAX
};

extern LPDIRECT3DTEXTURE9			g_pGameTexture[TEXTURE_MAX];

void Render();